name: Despliegue

on:
  push:
    branches:
      - main  # o 'master' según tu rama principal

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Setup Pages
      uses: actions/configure-pages@v3

    - name: Upload artifact
      uses: actions/upload-pages-artifact@v2
      with:
        path: .  # sube todo el contenido del repo

    - name: Deploy to GitHub Pages
      id: deployment
      uses: actions/deploy-pages@v2